---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Análise Imóveis Quinto Andar

## Carregar pacotes e dados 
```{r, warning=FALSE}
library(tidyverse, quietly = TRUE)
library(tidytext)
library(gt)
library(gtExtras)
library(EnvStats)

theme_set(
  theme_light() +
    theme(
      panel.grid.minor = element_blank()
    )
)

imoveis <- read_rds("dados/imoveis.rds") %>% 
  mutate(price_m2 = salePrice / area) %>% 
  relocate(price_m2, .after = id)

```

## Funções Úteis

```{r}
escala_dinheiro <- function(x){
  ifelse(x >= 1e6,
         paste0("R$", format(x / 1e6, big.mark = ",", scientific = FALSE, trim = TRUE), "M"),
         paste0("R$", format(x / 1e3, big.mark = ",", scientific = FALSE, trim = TRUE), "K"))
}

comparar_grupos <- function(tbl, col, x_label = ""){
  col_expr <- enquo(col)
  
  tbl %>% 
    ggplot(aes(factor(!!col_expr), salePrice, fill = factor(!!col_expr))) +
    geom_violin(width = 1.8, show.legend = FALSE) +
    geom_boxplot(width = 0.15,
                 alpha = 0.2,
                 color = "white",
                 show.legend = FALSE) +
    scale_y_log10(labels = escala_dinheiro) +
    stat_n_text(alpha = 0.5) +
    paletteer::scale_fill_paletteer_d("rcartocolor::Antique") +
    labs(x=x_label, y='Valor de venda')
}
```

## Relação de área do imóvel com valor de venda  

```{r}
imoveis %>% 
  filter(salePrice < 15e6) %>% 
  ggplot(aes(area, salePrice)) +
  geom_point(color = "brown", alpha = 0.2) +
  scale_y_log10(labels = escala_dinheiro) +
  scale_x_log10(labels = \(x) paste0(x, " m²")) +
  geom_smooth(method = "lm",
              color = "tomato",
              fill = "tomato", 
              alpha = 0.2) +
  labs(x='Área', y='Preço do Imóvel')
```

## Relação entre quantidade de quartos e preço do imóvel  

```{r}
imoveis %>% 
  comparar_grupos(bedrooms, x_label = "N° de Quartos")
```

## Relação entre quantidade de banheiros e preço do imóvel  

```{r}
imoveis %>% 
  comparar_grupos(bathrooms, x_label = "N° de Banheiros")
```


## Custo por região em SP

```{r}
imoveis_por_regiao <- imoveis %>% 
  summarize(
    price_m2 = mean(price_m2),
    yield = mean(yield),
    n = n(),
    .by = regionName
  ) %>% 
  filter(n > 15) %>% 
  arrange(desc(price_m2)) 
  
imoveis_por_regiao %>% 
  gt() %>% 
  cols_label(
    regionName = "Localização",
    price_m2   = "Preço do M²",
    yield      = "Rendimento do Imóvel",
    n          = "Quantidade"
  ) %>% 
  fmt_currency(
    columns = price_m2,
    decimals = 0,
    currency = "BRL"
  ) %>% 
  fmt_percent(
    columns = yield,
    decimals = 2,
    drop_trailing_zeros = TRUE
  ) %>%
  # tab_spanner(
  #   label = "Valores Medianos",
  #   columns = c(sale_price, total_cost)
  # ) %>% 
  tab_header(
    title = "Valor do m² de Apartamentos em diferentes regiões de SP"
  ) %>% 
  tab_source_note("Fonte: quintoandar.com.br") %>% 
  gt_theme_guardian()
```

## Preço médio por unidade de instalação no predio  

```{r}
library(tidytext)
imoveis %>% 
  unnest_tokens(palavra, installations) %>% 
  summarize(
    sale_price = mean(salePrice),
    .by = palavra
  ) %>% 
  mutate(palavra = str_to_sentence(str_replace_all(palavra, "_", " ")),
         palavra = fct_reorder(palavra, sale_price)) %>% 
  ggplot(aes(palavra, sale_price)) + 
  geom_segment(aes(x=palavra, xend=palavra, y=0, yend=sale_price),
               lty = 2) +
  geom_point(size = 3.6) +
  scale_y_continuous(labels = escala_dinheiro) +
  coord_flip() +
  labs(x='', y='')
```

## Preço de venda do imóvel x Rendimento do Aluguel  

```{r}
imoveis %>% 
  ggplot(aes(yield, price_m2)) +
  geom_point(size = 2.2, alpha = 0.3, color = "#824D74") +
  scale_y_continuous(labels = escala_dinheiro) +
  scale_x_continuous(labels = scales::percent_format()) +
  geom_smooth(method = "loess", color = "#401F71") +
  labs(x='Rentabilidade do imóvel', y='Preço m²')
```





